# Generated by Django 3.0.5 on 2020-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_reports_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='from_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
